name: ipp
base: core20
version: 1.0b1
summary: IPP Sample Implementation
description: |
  The ippsample project provides sample implementations of an IPP Client, Proxy,
  Server, and other tools. It is based on the CUPS source code and is maintained
  by the PWG IPP workgroup.

grade: stable
confinement: strict
icon: server/printer.png

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
    ipp3dprinter:
        command: bin/ipp3dprinter
        plugs: [avahi-observe, home, network, network-bind]
    ippdoclint:
        command: bin/ippdoclint
        plugs: [home]
    ippeveprinter:
        command: bin/ippeveprinter
        plugs: [avahi-observe, home, network, network-bind]
    ippfind:
        command: bin/ippfind
        plugs: [avahi-observe, home, network]
    ippproxy:
        command: sbin/ippproxy
        plugs: [avahi-observe, home, network]
    ippserver:
        command: sbin/ippserver
        plugs: [avahi-observe, home, network, network-bind]
    ipptool:
        command: bin/ipptool
        plugs: [home, network]
    ipptransform:
        command: bin/ipptransform
        plugs: [home, network]
    ipptransform3d:
        command: bin/ipptransform3d
        plugs: [home, network]

parts:
    main:
        plugin: autotools
        source: .
        source-submodules: [libcups, pdfio]
        build-packages: [cura-engine, libavahi-client-dev, libjpeg-dev, libpam-dev, libpng-dev, libssl-dev, libusb-1.0-0-dev, zlib1g-dev]
        stage-packages: [libavahi-client3, libjpeg-turbo8]
