name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: update build environment
      run: sudo apt-get update --fix-missing -y
    - name: install prerequisites
      run: sudo apt-get install -y avahi-daemon cppcheck libavahi-client-dev libjpeg-dev libpam-dev libpng-dev libssl-dev libusb-1.0-0-dev zlib1g-dev
    - name: configure
      env:
        CC: /usr/bin/gcc
      run: ./configure --enable-debug --enable-maintainer --enable-sanitizer --enable-static --disable-shared
    - name: make
      run: make
    - name: test
      run: make test || cat test/error_log*

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: install prerequisites
      run: brew install cppcheck libjpeg libpng libusb openssl
    - name: configure
      run: ./configure --enable-debug --enable-maintainer --enable-sanitizer --enable-static --disable-shared
    - name: make
      run: make
    - name: test
      run: make test || cat test/error_log*
