on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ippsample:latest
          outputs: type=docker,dest=/tmp/ippsample.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ippsample
          path: /tmp/ippsample.tar

  use:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ippsample
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/ippsample.tar
          docker image ls -a
